version: '3.8'

services:
  fastapi-auth:
    build: .
    ports:
      - "8888:8888"
    volumes:
      - ./app:/code/app
    command: ["fastapi", "run", "app/main.py",  "--port", "8888", "--workers", "1", "--reload",]
    networks:
      - ejbca-shared-network

networks:
  ejbca-shared-network:
    external: true