version: '3.8'

services:
  fastapi-auth:
    build: .
    volumes:
      - ./app:/code/app
      - ./config:/code/config
    environment:
      - ENV=prod
      - PROJECT_PATH=/code
    command: ["fastapi", "run", "app/main.py", "--port", "8888", "--workers", "1", "--reload"]
    networks:
      - internal-network
      - ejbca_shared_network

  nginx:
    image: nginx:alpine
    ports:
      - "443:443"
    volumes:
      # Mount your custom Nginx configuration file(s)
      - .nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      # Mount the directory containing your certificates (server.crt, server.key, ca.crt)
      - ./certificates:/etc/nginx/ssl:ro
    depends_on:
      - fastapi-auth
    networks:
      - internal-network

networks:
  internal-network:
    driver: bridge
  ejbca_shared_network:
    external: true
