name: Run Tests

on:
  push:
    branches:
      - main
      - dev
  pull_request:
    branches:
      - main
      - dev

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Start test environment
        run: docker-compose -f auth-server/docker-compose.ci.yml up --abort-on-container-exit

      - name: Cleanup
        run: docker-compose -f auth-server/docker-compose.ci.yml down -v
